addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.5")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"        % "0.7.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.5.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.6.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"              % "0.9.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"             % "1.3.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.3.1")
